###############################################################################
# DEFINITIONS
##############################################################################

host_image: &host_image "nativeci/cpp-meson:release-20220513.7"

##############################################################################
# MATRIX
##############################################################################
matrix:
  include:
  # Linux/compilers
  - CC: gcc
    CXX: g++
    IMAGE: *host_image
  - CC: clang
    CXX: clang++
    IMAGE: *host_image


##############################################################################
# PIPELINE
##############################################################################

pipeline:
  ############################################################################
  # Dependencies

  deps:
    image: ${IMAGE}
    environment:
    - DEBIAN_FRONTEND=noninteractive
    commands:
    - apt-get update -y
    - apt-get install -y libext2fs-dev

  ############################################################################
  # Build

  build:
    image: ${IMAGE}
    commands:
    - make


  ############################################################################
  # Tests

  test:
    image: ${IMAGE}
    commands:
    - make tests
